#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define COMMAND_BUF_SIZE 31+1
#define PARAMETERS_BUF_SIZE 127+1
#define DTA_BUF_SIZE 127+1

#define ENV_VAR_NAME_BUF_SIZE 31+1
#define ENV_VAR_CONTENT_BUF_SIZE 127+1

#endif